theme: jekyll-theme-minimal
# plugins:
#   - jekyll-remote-theme
# remote_theme: poole/hyde
title: [Gento Kato]
description: ["Ph.D. Student at Department of Political Science, University of California, Davis"]
